- hosts: all
  gather_facts: no
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - role: geerlingguy.pip
      tags: setup

  tasks:
    - name: copy env file to server
      ansible.builtin.template:
        src: templates/target.env.j2
        dest: /tmp/target.env
      become: yes
      tags: up

    - name: up docker container
      community.docker.docker_container:
        name: app
        image: "redmine"
        restart_policy: always
        state: started
        ports:
          - 80:3000
        env_file: /tmp/target.env
      become: yes    
      tags: up

- name: import datadog playbook
  ansible.builtin.import_playbook: datadog.yml
