- hosts: all
  gather_facts: no
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - role: geerlingguy.pip
      tags: setup

  tasks:
    - name: up docker container
      community.docker.docker_container:
        name: app
        image: "redmine"
        restart_policy: always
        state: started
        ports:
          - 80:3000
      become: yes    
      tags: up

